sudo: required
language: java
jdk:
  - openjdk11
before_script:
  - wget https://services.gradle.org/distributions/gradle-6.5-bin.zip
  - unzip gradle-6.5-bin.zip
  - export GRADLE_HOME=$PWD/gradle-6.5
  - export PATH=$GRADLE_HOME/bin:$PATH
addons:
  chrome: stable
  sonarcloud:
    organization: at-08
    token: "$SONAR_TOKEN"
before_install:
  - openssl aes-256-cbc -K $encrypted_15bdc0751ab4_key -iv $encrypted_15bdc0751ab4_iv
    -in environment.json.enc -out environment.json -d
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
script:
  - gradle compileJava compileTestJava
  - sonar-scanner
  - gradle check
  - gradle runFeatures
notifications:
  email: true
